spring:
  application:
    name: ecom-product-services

  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_product
    username: ecom_admin
    password: Vishalrdkp1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # use update ONLY for local testing
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    sql:
      init:
        mode: never

app:
  cors:
    allowed-origins: "http://localhost:3000" # comma-separated if multiple

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, mappings